name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v3
      - run: typst compile main.typ main.pdf
      # go to settings, action, set to read/write
      - uses: svenstaro/upload-release-action@v2
        with:
          release_name: "Calculus 2 - Matteo's Notes"
          file: main.pdf
          overwrite: true
